name: Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create release branch
      run: |
        git checkout -b release/v${{ inputs.version }}
        git push origin release/v${{ inputs.version }}

    - name: Update version
      run: |
        # Update Directory.Build.props
        sed -i 's|<VersionPrefix>.*</VersionPrefix>|<VersionPrefix>${{ inputs.version }}</VersionPrefix>|' Directory.Build.props
        
        # Update CHANGELOG.md
        today=$(date +%Y-%m-%d)
        sed -i "s/## \[Unreleased\]/## [Unreleased]\n\n## [${{ inputs.version }}] - $today/" CHANGELOG.md
        
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Prepare release v${{ inputs.version }}"
        git push

    - name: Create PR
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/v${{ inputs.version }}
        title: "Release v${{ inputs.version }}"
        body: |
          ## Release Checklist
          
          - [ ] Version updated in Directory.Build.props
          - [ ] CHANGELOG.md updated
          - [ ] All tests passing
          - [ ] Documentation reviewed
          - [ ] Breaking changes documented
          
          After merging, tag with: `git tag v${{ inputs.version }}`
